version: '3.5'

services:
  django:
    image: jandigarte/django:latest
    restart: always
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ../src/ARte/:/ARte/src/ARte/
      - ../locale/:/ARte/locale/
      - ./media/:/ARte/src/ARte/users/media/
    env_file:
      - ../src/.envs/.django
      - ../src/.envs/.postgres
      - ../src/.envs/.smtp
    depends_on:
      - postgres
    command: inv db -p i18n --compile docs collect run -p

  postgres:
    image: postgres:11.6
    env_file:
      - ../src/.envs/.postgres
    command: postgres -c max_connections=10000
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
